apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: physics-workflow-operator-workflow-editor-role
rules:
- apiGroups:
  - wp5.physics-faas.eu
  resources:
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wp5.physics-faas.eu
  resources:
  - workflows/status
  verbs:
  - get
