apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: physics-workflow-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Workflow is the Schema for the workflows API
      displayName: Workflow
      kind: Workflow
      name: workflows.wp5.physics-faas.eu
      version: v1alpha1
  description: physics-workflow-operator
  displayName: physics-workflow-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - physics
  links:
  - name: Physics Workflow Operator
    url: https://physics-workflow-operator.domain
  maturity: alpha
  provider:
    name: physics
  version: 0.0.0
