apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  namespace: okdmoc-spoke-cluster
  name: example-manifestwork
spec:
  workload:
    manifests:
      - apiVersion: v1
        kind: ServiceAccount
        metadata:
          namespace: physics-atos
          name: my-sa
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          namespace: physics-atos
          name: nginx-deployment
          labels:
            app: nginx
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
            spec:
              serviceAccountName: my-sa
              containers:
                - name: nginx
                  image: nginx:1.14.2
                  ports:
                    - containerPort: 80